# Generated by Django 5.1.7 on 2025-04-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_all_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_news',
            name='category',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
